[Weathers]

; The options in this section act as global toggles for all volume-related options.

; These options control which weather types have volumes enabled.
ExtraSunnyHasVolumes = 0
SunnyHasVolumes	     = 0
SunnyWindyHasVolumes = 0
CloudyHasVolumes	 = 0
RainHasVolumes	     = 1
DrizzleHasVolumes    = 1
FoggyHasVolumes      = 1
LightningHasVolumes  = 1

[Spotlights]

; The options in this section apply only to the affected models containing spotlights.

; These options allow adjusting the volume intensity of the affected spotlights for each weather type (0.0 | 1.0).
VolumeIntensityExtraSunny = 0.0
VolumeIntensitySunny	  = 0.0
VolumeIntensitySunnyWindy = 0.0
VolumeIntensityCloudy	  = 0.0
VolumeIntensityRain		  = 0.15
VolumeIntensityDrizzle	  = 0.1
VolumeIntensityFoggy	  = 0.3
VolumeIntensityLightning  = 0.2

; These options allow adjusting the volume scale of the affected spotlights for each weather type (0.0 | 1.0).
VolumeScaleExtraSunny = 0.0
VolumeScaleSunny	  = 0.0
VolumeScaleSunnyWindy = 0.0
VolumeScaleCloudy	  = 0.0
VolumeScaleRain		  = 0.15
VolumeScaleDrizzle	  = 0.1
VolumeScaleFoggy	  = 0.3
VolumeScaleLightning  = 0.2

; These options allow adjusting the cone widths of the affected spotlights (0.0 | 179.0).
; This affects both the spotlights' cone width and the width/shape of their volumes.
; Note that using custom options for these particular aspects may not look right for all affected models.
; Set to -1.0 to respect the values set inside their models, otherwise set to any preferred value.
; These options are aesthetic and have no impact on performance.
InnerConeAngle = -1.0
OuterConeAngle = -1.0

; These options allow adjusting the corona properties of the affected spotlights.
; Set to -1.0 to respect the values set inside their models, otherwise set to any preferred value.
; These options can have an impact on performance when set high enough.
; (0.0 | 100.0)
CoronaSize = -1.0
; (0.0 | 16.0)
CoronaIntensity = -1.0

[Pointlights]

; The options in this section apply only to the affected models containing pointlights.

; These options allow adjusting the volume intensity of the affected pointlights for each weather type (0.0 | 1.0).
VolumeIntensityExtraSunny = 0.0
VolumeIntensitySunny	  = 0.0
VolumeIntensitySunnyWindy = 0.0
VolumeIntensityCloudy	  = 0.0
VolumeIntensityRain		  = 0.3
VolumeIntensityDrizzle	  = 0.25
VolumeIntensityFoggy	  = 0.45
VolumeIntensityLightning  = 0.35

; These options allow adjusting the volume scale of the affected pointlights for each weather type (0.0 | 1.0).
VolumeScaleExtraSunny = 0.0
VolumeScaleSunny	  = 0.0
VolumeScaleSunnyWindy = 0.0
VolumeScaleCloudy	  = 0.0
VolumeScaleRain		  = 0.15
VolumeScaleDrizzle	  = 0.1
VolumeScaleFoggy	  = 0.3
VolumeScaleLightning  = 0.2

; These options allow adjusting the corona properties of the affected pointlights.
; Set to -1.0 to respect the values set inside their models, otherwise set to any preferred value.
; These options can have an impact on performance when set high enough.
; (0.0 | 100.0)
CoronaSize = -1.0
; (0.0 | 16.0)
CoronaIntensity = -1.0

[Shared]

; The options in this section apply to all affected light models.

; This option allows adjusting whether the lights begin fading in/out earlier than their models do, or if they fade in/out along with their models (-1.0 | 1000.0).
; Set to -1.0 so that the lights begin fading in/out along with their models (Late fading), otherwise set to any preferred value (Early fading).
; The vanilla game's lights have this set to 1/2 their models' draw distances as set in .ide files, in case this formula is preferred.
; This option does not impact performance considerably.
LightFadeDistance = -1.0

; This option allows adjusting whether the volumes begin fading in/out earlier than their lights/models do, or if they fade in/out along with their lights/models (-1.0 | 1000.0).
; Set to -1.0 so that the volumes begin fading in/out along with their lights/models (Late fading), otherwise set to any preferred value (Early fading).
; The vanilla game's volumes have this set to 1/10 the models' draw distances as set in .ide files, in case this formula is preferred.
; This option can have an impact on performance.
VolumeFadeDistance = -1.0

[VehicleLights]

; The options in this sections apply to various vehicle lights.

; This option adds specular to vehicle siren lights and for some siren types/vehicles, it positions them at the right location "inside" the sirens' casings.
UnfakeVehicleSirenLights = 1

[Misc]

; The options in this section are included for convenience since they're still related to lights, but are not strictly the point of the mod.

; This option adjusts the look of the lights attached to pickups (0 - Off | 1 - Default | 2 - Default without specular, makes the lights look more "fake" as they probably should).
PickupLightsMode = 1
